name: baka_animestream
description: Un app per guardare anime

publish_to: "none"

version: 1.1.0+1

environment:
  sdk: ">=2.18.0-44.1.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dynamic_color: ^1.4.0
  cached_network_image: ^3.2.1
  requests: ^4.4.1
  html: ^0.15.0
  expandable_widgets: ^1.0.3+1
  better_player: ^0.0.83
  animated_text_kit: ^4.2.2
  http: ^0.13.6
  get: ^4.6.5
  shared_preferences: ^2.1.1
  dynamic_themes: ^1.1.0
  device_info_plus: ^8.2.2
  package_info_plus: ^3.1.2
  webview_flutter_plus: ^0.3.0+2
  objectbox: ^2.0.0
  objectbox_flutter_libs: any
  path: ^1.8.2
  path_provider: ^2.0.15
  fluttertoast: ^8.2.2
  url_launcher: ^6.1.11
  flutter_bloc: ^8.1.3
  ota_update: ^5.1.0
  file_picker: ^5.2.10
  restart_app: ^1.1.2
  permission_handler: ^10.2.0
  archive: ^3.3.7
  media_kit_libs_android_video: ^1.0.5
  media_kit_libs_ios_video: ^1.0.4
  flutter_meedu_videoplayer:
    git:
      url: https://github.com/aleeeee1/flutter_meedu_videoplayer.git
      ref: master
      path: ./package/
  # flutter_meedu_videoplayer:
  #   path: ./forks/flutter_meedu_videoplayer/package

  flutter_native_splash: ^2.2.19
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path_ios: "assets/images/splash.png"
  image_path_android: "assets/images/splash.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  objectbox_generator: any
  animated_native_splash:
    git: https://github.com/asbn223/flutter_animated_splash_screen

flutter:
  uses-material-design: true

animated_native_splash:
  jsonFile: assets/splash2.json
