name: baka_animestream
description: Un app per guardare anime

publish_to: "none"

version: 2.0.0+1

environment:
  sdk: ">=2.18.0-44.1.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dynamic_color: ^1.4.0
  cached_network_image: ^3.2.1
  requests: ^4.4.1
  html: ^0.15.0
  expandable_widgets: ^1.0.3+1
  better_player: ^0.0.83
  animated_text_kit: ^4.2.2
  http: ^0.13.6
  get: ^4.6.5
  shared_preferences: ^2.1.1
  dynamic_themes: ^1.1.0
  device_info_plus: ^8.2.2
  package_info_plus: ^3.1.2
  webview_flutter_plus: ^0.3.0+2
  objectbox: ^2.0.0
  objectbox_flutter_libs: any
  path: ^1.8.2
  path_provider: ^2.0.15
  fluttertoast: ^8.2.2
  url_launcher: ^6.1.11
  flutter_bloc: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  objectbox_generator: any

flutter:
  uses-material-design: true
