name: Flutter CI

on:
  push:
    branches:
      - master
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: ncipollo/release-action@v1
          with:
            token: ${{ secrets.TOKEN }}
            commit: master
            tag: v2.0.0
